micronaut:
  application:
    name: todoTest
  security:
    authentication: bearer
    token:
      jwt:
        generator:
          access-token:
            expiration: 8640000
        signatures:
          secret:
            generator:
              secret: "${JWT_SECRET}"
    endpoints:
      login:
        path: "/api/auth/login"
  server:
    cors:
      enabled: true
    port: "${PORT}"
datasources:
  default:
    url: "${DB_CONN_URL}"
    driverClassName: oracle.jdbc.driver.OracleDriver
    username: "${DB_USERNAME}"
    password: "${DB_PASSWORD}"
    dialect: org.hibernate.dialect.Oracle10gDialect
jpa:
  default:
    packages-to-scan:
      - 'rltw.todo'
    properties:
      hibernate:
        hbm2ddl:
          auto: update
        show_sql: true
